version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/app_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    volumes:
      - ./app:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  redis:
    image: redis:7.4.1
    container_name: redis_server
    ports:
      - "6379:6379"
volumes:
  db_data:
  redis_data:
